### ISSUE TITLE
simple demo

### ISSUE THREAD

**Issue by iorch** [EliasKotlyar/yowsup-queue#5]
Hey @EliasKotlyar , great work. 

Do you have a simple demo for sending/reading messages to/from the queues? I heaven´t used beanstalk nor queues before.

Thanks.

**Comment by RiBro** [comment]
'''
#!/usr/bin/python3

from pystalkd.Beanstalkd import Connection
import json
import sys
import os
from datetime import datetime

ARCHIVEDIR='~/whatsAppArchive'


def createFile  (archiveDir, message):
    phonenumber=message['address'].split('@')[0]
    dirName=archiveDir+'/'+phonenumber
    dir = os.path.dirname(dirName)

    try:
        os.stat(dirName)
    except:
        os.mkdir(dirName)
        file = open(dirName+'/archive.txt', "a")
        file.writelines(message['address']+ '\n')
        file.close()
    file = open(dirName+'/archive.txt', "a")
    file.writelines("["+message['timestamp']+"] " +message['body']+ '\n')
    file.close()


c = Connection("localhost", 11300)
c.use('whatsapp-send')
c.watch('whatsapp-receive')


while(true):
    job=c.reserve(0.05)
    if not job is None:
        try:
            messageBody = str(job.body)
            message = json.loads(messageBody)
            if message["type"] == "simple":
                createFile (ARCHIVEDIR, message)
            else:
                raise Exception("Unrecognized Message: %s" % message)
            job.delete()

        except Exception as e:
            job.bury()
            traceback.print_exc()
    else:
        break
'''

**Comment by iorch** [comment]
Thanks a lot.
