### ISSUE TITLE
JSON examples for media

### ISSUE THREAD

**Issue by spkprav** [EliasKotlyar/yowsup-queue#7]
Hi, help wanted on how to send media through this application.
Please provide some example JSON.

**Comment by EliasKotlyar** [comment]
Hello 

It was not possible with the Version. But i has taken your Request as a Feature Request and implemented the Function. 

Please have a try with the updated Version and the following XML:


{"type":"image","body":"This is a Test-Message!","image":"\/9j\/4AAQSkZJRgABAQAAAQABAAD\/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7\/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7\/wAARCAASAA4DASIAAhEBAxEB\/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL\/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6\/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL\/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6\/9oADAMBAAIRAxEAPwD23xz+0b8LPBuu3eh6xrN02oWkhjnht7R5CjA4IzgDrXOD9r34O5\/4+9b\/APBef\/iq4z9m3QdC8SftEfGweINE03Vlt9ak8kX1qk\/l\/wClXAO3eDjgDp6Cvov\/AIVx8PMf8iH4W\/8ABRB\/8RQB4L+yV\/ycV8c\/+w1J\/wCldzX1GKKKAP\/Z","address":"<img>@s.whatsapp.net"}

**Comment by spkprav** [comment]
Hi, Thanks for the update. This will be really helpful for me.
