### ISSUE TITLE
double check back

### ISSUE THREAD

**Issue by Tokay-tech** [EliasKotlyar/yowsup-queue#9]
Hello,
Is it possible to send back a blue double check when the message is read from queue?

**Comment by EliasKotlyar** [comment]
Hello,

This is not technically not possible,because the queue can be processed even if the whatsapp service has crashed.

However it should be possible to implement a feature which can send a blue double check if you send a special message to the queue.

Greetings
Elias

**Comment by Tokay-tech** [comment]
Thank you for the answer,
this feature will be included in the next release?
